proxies:
  - name: "cleardewy_vpn"
    type: ss
    server: 172.203.209.17
    port: 1107
    cipher: chacha20-ietf-poly1305
    password: "040110"
    udp: true

# 代理组配置
proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "cleardewy_vpn"

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip # 或者使用 redir-host
  nameserver:
    - "8.8.8.8"
    - "1.1.1.1"
    - "114.114.114.114"
    - "8.8.4.4"

rules:
    - 'MATCH,Proxy'
